import type { DrinkComponent } from "@/lib/types";

/*
  Building blocks for the Shake and Drink Mixer.
  perServing values are per single measure added to the glass.
*/
export const drinkComponents: DrinkComponent[] = [
  {
    id: "oat-milk",
    name: "Oat milk",
    kind: "base",
    color: "#efe6d2",
    flavor: { sweet: 3, fat: 4 },
    perServing: { calories: 90, protein: 3, carbs: 14, fat: 3, sugar: 5 },
    note: "Creamy neutral base that keeps things plant forward.",
  },
  {
    id: "whole-milk",
    name: "Whole milk",
    kind: "base",
    color: "#fbf7ec",
    flavor: { sweet: 2, fat: 6, umami: 1 },
    perServing: { calories: 120, protein: 6, carbs: 9, fat: 6, sugar: 9 },
    note: "Classic diner shake body with real richness.",
  },
  {
    id: "coconut-water",
    name: "Coconut water",
    kind: "base",
    color: "#f2f6ef",
    flavor: { sweet: 3, sour: 1 },
    perServing: { calories: 45, protein: 1, carbs: 9, fat: 0, sugar: 8 },
    note: "Light and electrolyte rich for hot day drinks.",
  },
  {
    id: "cold-brew",
    name: "Cold brew coffee",
    kind: "base",
    color: "#3a2416",
    flavor: { bitter: 6, umami: 2 },
    perServing: { calories: 5, protein: 0, carbs: 1, fat: 0 },
    note: "Low acid coffee punch for wake up shakes.",
  },
  {
    id: "banana",
    name: "Frozen banana",
    kind: "fruit",
    color: "#f4e07a",
    flavor: { sweet: 7, fat: 1 },
    perServing: { calories: 105, protein: 1, carbs: 27, fat: 0, sugar: 14, fiber: 3 },
    note: "Thickener and natural sweetener in one.",
  },
  {
    id: "strawberry",
    name: "Strawberries",
    kind: "fruit",
    color: "#e5484d",
    flavor: { sweet: 5, sour: 4 },
    perServing: { calories: 25, protein: 1, carbs: 6, fat: 0, sugar: 4, fiber: 2 },
    note: "Bright berry tang and a soft pink hue.",
  },
  {
    id: "pineapple",
    name: "Pineapple",
    kind: "fruit",
    color: "#f6c945",
    flavor: { sweet: 6, sour: 5 },
    perServing: { calories: 40, protein: 0, carbs: 11, fat: 0, sugar: 8, fiber: 1 },
    note: "Tropical acidity that wakes up a green shake.",
  },
  {
    id: "mango",
    name: "Mango",
    kind: "fruit",
    color: "#f2a33c",
    flavor: { sweet: 7, sour: 2 },
    perServing: { calories: 60, protein: 1, carbs: 15, fat: 0, sugar: 13, fiber: 2 },
    note: "Silky sweetness with a golden color.",
  },
  {
    id: "spinach",
    name: "Baby spinach",
    kind: "green",
    color: "#3f7d3f",
    flavor: { bitter: 2, umami: 1 },
    perServing: { calories: 7, protein: 1, carbs: 1, fat: 0, fiber: 1 },
    note: "Mild greens that vanish into fruit flavor.",
  },
  {
    id: "mint",
    name: "Fresh mint",
    kind: "green",
    color: "#4faa6a",
    flavor: { bitter: 1, sour: 1 },
    perServing: { calories: 2, protein: 0, carbs: 0, fat: 0 },
    note: "Cooling lift for coolers and green shakes.",
  },
  {
    id: "whey",
    name: "Vanilla whey",
    kind: "booster",
    color: "#f0e4cf",
    flavor: { sweet: 4, fat: 2 },
    perServing: { calories: 120, protein: 24, carbs: 3, fat: 1, sugar: 2 },
    note: "Straightforward protein for recovery shakes.",
  },
  {
    id: "peanut-butter",
    name: "Peanut butter",
    kind: "booster",
    color: "#c58a4a",
    flavor: { sweet: 2, salty: 3, fat: 7, umami: 3 },
    perServing: { calories: 190, protein: 8, carbs: 7, fat: 16, sugar: 3, fiber: 2 },
    note: "Roasty depth and staying power.",
  },
  {
    id: "cacao",
    name: "Raw cacao",
    kind: "booster",
    color: "#4a2c1d",
    flavor: { bitter: 6, umami: 2 },
    perServing: { calories: 50, protein: 3, carbs: 10, fat: 3, fiber: 4 },
    note: "Deep chocolate without the sugar.",
  },
  {
    id: "chia",
    name: "Chia seeds",
    kind: "booster",
    color: "#3b3a36",
    flavor: {},
    perServing: { calories: 60, protein: 2, carbs: 5, fat: 4, fiber: 5 },
    note: "Fiber and a pudding like thickness.",
  },
  {
    id: "honey",
    name: "Raw honey",
    kind: "sweetener",
    color: "#e8a13a",
    flavor: { sweet: 9 },
    perServing: { calories: 64, protein: 0, carbs: 17, fat: 0, sugar: 17 },
    note: "Floral sweetness that rounds sharp fruit.",
  },
  {
    id: "maple",
    name: "Maple syrup",
    kind: "sweetener",
    color: "#c26a2e",
    flavor: { sweet: 8, umami: 1 },
    perServing: { calories: 52, protein: 0, carbs: 13, fat: 0, sugar: 12 },
    note: "Warm caramel notes for autumn drinks.",
  },
  {
    id: "date",
    name: "Medjool date",
    kind: "sweetener",
    color: "#5a3320",
    flavor: { sweet: 8, umami: 2 },
    perServing: { calories: 66, protein: 0, carbs: 18, fat: 0, sugar: 16, fiber: 2 },
    note: "Toffee sweetness plus fiber and body.",
  },
  {
    id: "ginger",
    name: "Fresh ginger",
    kind: "spice",
    color: "#e0c48c",
    flavor: { spicy: 6, sour: 1 },
    perServing: { calories: 5, protein: 0, carbs: 1, fat: 0 },
    note: "Sharp heat that cuts through sweetness.",
  },
  {
    id: "cinnamon",
    name: "Cinnamon",
    kind: "spice",
    color: "#9c5a2d",
    flavor: { sweet: 2, spicy: 3, bitter: 1 },
    perServing: { calories: 6, protein: 0, carbs: 2, fat: 0, fiber: 1 },
    note: "Cozy warmth for golden and malt drinks.",
  },
  {
    id: "turmeric",
    name: "Turmeric",
    kind: "spice",
    color: "#d99a1e",
    flavor: { bitter: 3, spicy: 2, umami: 1 },
    perServing: { calories: 8, protein: 0, carbs: 1, fat: 0 },
    note: "Earthy color and a gentle bitter edge.",
  },
  {
    id: "crushed-ice",
    name: "Crushed ice",
    kind: "ice",
    color: "#dfeef5",
    flavor: {},
    perServing: { calories: 0, protein: 0, carbs: 0, fat: 0 },
    note: "Dilution and a frosty slush texture.",
  },
];
