import type { Recipe } from "@/lib/types";

/*
  Bundled seed recipes. The site runs entirely on these until a Sanity project
  is connected, at which point the same shape is fetched from the CMS instead.
*/
export const recipes: Recipe[] = [
  {
    _id: "seed-butter-chicken",
    slug: "weeknight-butter-chicken",
    title: "Weeknight Butter Chicken",
    dishType: "food",
    cuisine: "Indian",
    category: "Mains",
    dietTags: ["gluten-free"],
    moodTags: ["cozy", "comfort", "indulgent"],
    difficulty: "medium",
    prepMinutes: 20,
    cookMinutes: 30,
    servings: 4,
    heroImage: "",
    heroAlt: "A bowl of glossy orange butter chicken topped with cream and coriander",
    intro:
      "A faster take on the restaurant classic. The sauce leans on bloomed spices and a splash of cream rather than an overnight marinade, so it lands on the table in under an hour.",
    ingredients: [
      { quantity: 700, unit: "g", item: "boneless chicken thigh", note: "cut into chunks" },
      { quantity: 1, unit: "cup", item: "plain yogurt", group: "Marinade" },
      { quantity: 2, unit: "tsp", item: "garam masala", group: "Marinade" },
      { quantity: 1, unit: "tbsp", item: "grated ginger", group: "Marinade", pantry: true },
      { quantity: 4, unit: null, item: "garlic cloves", note: "crushed", pantry: true },
      { quantity: 2, unit: "tbsp", item: "butter", group: "Sauce", pantry: true },
      { quantity: 1, unit: null, item: "large onion", note: "finely diced", group: "Sauce", pantry: true },
      { quantity: 400, unit: "g", item: "crushed tomatoes", group: "Sauce" },
      { quantity: 1, unit: "tsp", item: "smoked paprika", group: "Sauce", pantry: true },
      { quantity: 0.5, unit: "cup", item: "heavy cream", group: "Sauce" },
      { quantity: 1, unit: "tsp", item: "sugar", group: "Sauce", pantry: true },
      { quantity: null, unit: null, item: "coriander and warm naan", note: "to serve" },
    ],
    steps: [
      { instruction: "Toss the chicken with yogurt, garam masala, half the ginger, and half the garlic. Let it sit while you prep everything else.", durationMinutes: 15 },
      { instruction: "Melt butter in a wide pan over medium heat. Add onion with a pinch of salt and cook until soft and golden.", durationMinutes: 8, technique: "deglaze" },
      { instruction: "Stir in the remaining ginger and garlic, the paprika, and a spoon of garam masala. Bloom for thirty seconds until fragrant.", durationMinutes: 1, technique: "bloom-spices" },
      { instruction: "Add crushed tomatoes and sugar. Simmer until the sauce darkens and thickens, then blend smooth if you like a silky finish.", durationMinutes: 10, technique: "reduce" },
      { instruction: "Slide in the chicken and its marinade. Cook gently until the pieces are just done.", durationMinutes: 12 },
      { instruction: "Off the heat, swirl in the cream and taste for salt. Rest five minutes, then finish with coriander.", durationMinutes: 5 },
    ],
    equipment: ["Wide sauté pan", "Blender (optional)"],
    tips: [
      "No cream on hand works with full fat coconut milk, which nudges the dish dairy light.",
      "Double the sauce and freeze half for an even faster round two.",
    ],
    nutrition: { calories: 540, protein: 41, carbs: 18, fat: 34, sugar: 9, fiber: 3 },
    flavor: { sweet: 4, salty: 5, sour: 3, bitter: 1, umami: 7, fat: 7, spicy: 3 },
    author: "The Dish It Kitchen",
    featured: true,
    publishedAt: "2026-02-10",
  },
  {
    _id: "seed-elote-bowl",
    slug: "charred-corn-elote-bowl",
    title: "Charred Corn Elote Bowl",
    dishType: "food",
    cuisine: "Mexican",
    category: "Bowls",
    dietTags: ["vegetarian", "gluten-free"],
    moodTags: ["fresh", "quick", "comfort"],
    difficulty: "easy",
    prepMinutes: 10,
    cookMinutes: 12,
    servings: 2,
    heroImage: "",
    heroAlt: "A bowl of charred corn with lime crema, cotija, and chili",
    intro:
      "Everything you love about street corn, loosened into a bowl you can eat with a spoon. Char the kernels hard so they keep a smoky bite under the dressing.",
    ingredients: [
      { quantity: 4, unit: "cups", item: "corn kernels", note: "fresh or thawed" },
      { quantity: 1, unit: "tbsp", item: "neutral oil", pantry: true },
      { quantity: 3, unit: "tbsp", item: "mayonnaise" },
      { quantity: 2, unit: "tbsp", item: "sour cream" },
      { quantity: 1, unit: null, item: "lime", note: "zest and juice", pantry: true },
      { quantity: 0.5, unit: "tsp", item: "chili powder", pantry: true },
      { quantity: 0.5, unit: "cup", item: "crumbled cotija", note: "or feta" },
      { quantity: null, unit: null, item: "coriander and pickled jalapeno", note: "to serve" },
    ],
    steps: [
      { instruction: "Heat oil in a cast iron pan until it shimmers. Add corn in one layer and leave it alone so it blisters.", durationMinutes: 6 },
      { instruction: "Toss once, then char the second side. You want dark spots, not a full stir fry.", durationMinutes: 4 },
      { instruction: "Whisk mayo, sour cream, lime juice and zest, and chili powder into a loose dressing.", durationMinutes: 2, technique: "emulsify" },
      { instruction: "Fold the warm corn into the dressing. Top with cotija, coriander, and jalapeno.", durationMinutes: 1, technique: "fold" },
    ],
    equipment: ["Cast iron pan"],
    tips: ["Leftover bowl folds straight into scrambled eggs the next morning."],
    nutrition: { calories: 430, protein: 12, carbs: 44, fat: 25, sugar: 10, fiber: 6 },
    flavor: { sweet: 6, salty: 6, sour: 5, bitter: 2, umami: 5, fat: 6, spicy: 3 },
    author: "The Dish It Kitchen",
    featured: false,
    publishedAt: "2026-03-01",
  },
  {
    _id: "seed-miso-ramen",
    slug: "miso-mushroom-ramen",
    title: "Miso Mushroom Ramen",
    dishType: "food",
    cuisine: "Japanese",
    category: "Soups",
    dietTags: ["vegetarian", "vegan-option"],
    moodTags: ["cozy", "comfort", "post-gym"],
    difficulty: "medium",
    prepMinutes: 15,
    cookMinutes: 25,
    servings: 2,
    heroImage: "",
    heroAlt: "A steaming bowl of miso ramen with mushrooms, corn, and a soft egg",
    intro:
      "A weeknight broth that tastes long simmered thanks to roasted mushrooms and a spoonful of miso stirred in at the very end so it stays alive.",
    ingredients: [
      { quantity: 300, unit: "g", item: "mixed mushrooms", note: "torn" },
      { quantity: 1, unit: "tbsp", item: "sesame oil", pantry: true },
      { quantity: 1, unit: "l", item: "vegetable stock" },
      { quantity: 3, unit: "tbsp", item: "white miso" },
      { quantity: 1, unit: "tbsp", item: "soy sauce", pantry: true },
      { quantity: 1, unit: "tsp", item: "grated ginger", pantry: true },
      { quantity: 2, unit: null, item: "garlic cloves", note: "sliced", pantry: true },
      { quantity: 2, unit: "portions", item: "ramen noodles" },
      { quantity: null, unit: null, item: "soft egg, corn, spring onion", note: "to serve" },
    ],
    steps: [
      { instruction: "Sear the mushrooms in sesame oil over high heat until deeply browned and shrunk by half.", durationMinutes: 8 },
      { instruction: "Add garlic and ginger, cook one minute, then pour in the stock and soy. Simmer to build flavor.", durationMinutes: 12, technique: "reduce" },
      { instruction: "Cook the noodles separately in salted water, then divide between bowls.", durationMinutes: 4 },
      { instruction: "Whisk the miso with a ladle of hot broth until smooth, then stir it back into the pot off the heat.", durationMinutes: 1, technique: "temper" },
      { instruction: "Pour broth over the noodles and add your toppings.", durationMinutes: 1 },
    ],
    equipment: ["Large pot", "Wide skillet"],
    tips: ["Keep miso away from a hard boil or it loses its brightness and turns flat."],
    nutrition: { calories: 470, protein: 18, carbs: 62, fat: 16, sugar: 8, fiber: 6 },
    flavor: { sweet: 2, salty: 8, sour: 1, bitter: 2, umami: 9, fat: 4, spicy: 1 },
    author: "The Dish It Kitchen",
    featured: true,
    publishedAt: "2026-01-20",
  },
  {
    _id: "seed-black-bean-tacos",
    slug: "smoky-black-bean-tacos",
    title: "Smoky Black Bean Tacos",
    dishType: "food",
    cuisine: "Mexican",
    category: "Mains",
    dietTags: ["vegan", "dairy-free"],
    moodTags: ["quick", "fresh", "comfort"],
    difficulty: "easy",
    prepMinutes: 10,
    cookMinutes: 15,
    servings: 3,
    heroImage: "",
    heroAlt: "Three corn tortillas filled with smoky black beans, slaw, and avocado",
    intro:
      "Pantry tacos with real depth. Chipotle and a squeeze of lime turn a can of beans into a filling nobody guesses was fifteen minutes of work.",
    ingredients: [
      { quantity: 2, unit: "cans", item: "black beans", note: "drained" },
      { quantity: 1, unit: null, item: "onion", note: "diced", pantry: true },
      { quantity: 2, unit: null, item: "chipotle in adobo", note: "chopped" },
      { quantity: 1, unit: "tsp", item: "cumin", pantry: true },
      { quantity: 1, unit: "tbsp", item: "olive oil", pantry: true },
      { quantity: 9, unit: null, item: "corn tortillas" },
      { quantity: 2, unit: "cups", item: "shredded cabbage" },
      { quantity: 1, unit: null, item: "lime", pantry: true },
      { quantity: 1, unit: null, item: "avocado", note: "sliced" },
    ],
    steps: [
      { instruction: "Soften the onion in olive oil, then add cumin and chipotle and stir until fragrant.", durationMinutes: 5, technique: "bloom-spices" },
      { instruction: "Add the beans with a splash of water. Simmer and mash a third of them for a creamy body.", durationMinutes: 8 },
      { instruction: "Toss cabbage with lime juice and a pinch of salt for a quick slaw.", durationMinutes: 2 },
      { instruction: "Char the tortillas over a flame or in a dry pan, then build with beans, slaw, and avocado.", durationMinutes: 3 },
    ],
    equipment: ["Skillet"],
    tips: ["A crumble of cotija or a dollop of yogurt is welcome if you are not keeping it vegan."],
    nutrition: { calories: 400, protein: 15, carbs: 58, fat: 13, sugar: 4, fiber: 15 },
    flavor: { sweet: 2, salty: 5, sour: 4, bitter: 1, umami: 5, fat: 4, spicy: 5 },
    author: "The Dish It Kitchen",
    featured: false,
    publishedAt: "2026-03-14",
  },
  {
    _id: "seed-roast-chicken",
    slug: "lemon-herb-roast-chicken",
    title: "Lemon Herb Roast Chicken",
    dishType: "food",
    cuisine: "Mediterranean",
    category: "Mains",
    dietTags: ["gluten-free", "dairy-free"],
    moodTags: ["celebration", "cozy", "comfort"],
    difficulty: "medium",
    prepMinutes: 15,
    cookMinutes: 75,
    servings: 4,
    heroImage: "",
    heroAlt: "A golden roast chicken with lemon halves and herbs on a board",
    intro:
      "The one recipe worth memorizing. A dry brine the night before is the only trick, and it turns an ordinary bird into something with shatteringly crisp skin.",
    ingredients: [
      { quantity: 1.6, unit: "kg", item: "whole chicken" },
      { quantity: 1, unit: "tbsp", item: "flaky salt", pantry: true },
      { quantity: 1, unit: null, item: "lemon", note: "halved", pantry: true },
      { quantity: 1, unit: "head", item: "garlic", note: "halved crosswise", pantry: true },
      { quantity: 1, unit: "small bunch", item: "thyme and rosemary" },
      { quantity: 2, unit: "tbsp", item: "olive oil", pantry: true },
      { quantity: 500, unit: "g", item: "baby potatoes", note: "halved" },
    ],
    steps: [
      { instruction: "The day before, pat the chicken dry and salt it all over. Rest uncovered in the fridge overnight.", durationMinutes: 10 },
      { instruction: "Heat the oven to 220C. Stuff the cavity with lemon, garlic, and herbs, then rub the skin with oil.", durationMinutes: 5 },
      { instruction: "Scatter potatoes around the bird. Roast until the thickest part of the thigh reads 74C.", durationMinutes: 70 },
      { instruction: "Move the chicken to a board and rest it loosely tented while you crisp the potatoes in the drippings.", durationMinutes: 15, technique: "rest-meat" },
      { instruction: "Carve and spoon the pan juices over the top.", durationMinutes: 5 },
    ],
    equipment: ["Roasting tray", "Instant read thermometer"],
    tips: ["Save the carcass. Simmered with an onion and a carrot it becomes stock for the ramen above."],
    nutrition: { calories: 610, protein: 46, carbs: 27, fat: 35, sugar: 2, fiber: 4 },
    flavor: { sweet: 2, salty: 6, sour: 3, bitter: 1, umami: 7, fat: 7, spicy: 0 },
    author: "The Dish It Kitchen",
    featured: true,
    publishedAt: "2026-02-24",
  },
  {
    _id: "seed-crispy-gnocchi",
    slug: "crispy-gnocchi-with-sage",
    title: "Crispy Gnocchi with Sage Butter",
    dishType: "food",
    cuisine: "Italian",
    category: "Mains",
    dietTags: ["vegetarian"],
    moodTags: ["quick", "indulgent", "cozy"],
    difficulty: "easy",
    prepMinutes: 5,
    cookMinutes: 15,
    servings: 2,
    heroImage: "",
    heroAlt: "Golden pan fried gnocchi with crisp sage leaves and brown butter",
    intro:
      "Skip the boiling water. Shelf stable gnocchi crisps up like a tiny potato roast straight in the pan, then gets tossed in nutty brown butter.",
    ingredients: [
      { quantity: 500, unit: "g", item: "shelf stable gnocchi" },
      { quantity: 3, unit: "tbsp", item: "butter", pantry: true },
      { quantity: 12, unit: null, item: "sage leaves" },
      { quantity: 2, unit: null, item: "garlic cloves", note: "smashed", pantry: true },
      { quantity: 1, unit: "handful", item: "grated parmesan" },
      { quantity: null, unit: null, item: "lemon and black pepper", note: "to finish", pantry: true },
    ],
    steps: [
      { instruction: "Heat a dry nonstick pan, add gnocchi, and let them blister before tossing. They will puff slightly.", durationMinutes: 7 },
      { instruction: "Add butter, sage, and garlic. Swirl until the butter foams, smells nutty, and turns amber.", durationMinutes: 4, technique: "reduce" },
      { instruction: "Kill the heat, add a squeeze of lemon and the parmesan, and toss to coat.", durationMinutes: 1 },
    ],
    equipment: ["Nonstick skillet"],
    tips: ["A big handful of spinach wilted in at the end makes it feel like a full plate."],
    nutrition: { calories: 560, protein: 14, carbs: 74, fat: 24, sugar: 3, fiber: 4 },
    flavor: { sweet: 2, salty: 6, sour: 2, bitter: 2, umami: 6, fat: 8, spicy: 1 },
    author: "The Dish It Kitchen",
    featured: false,
    publishedAt: "2026-03-20",
  },
  {
    _id: "seed-harissa-salmon",
    slug: "one-pan-harissa-salmon",
    title: "One Pan Harissa Salmon",
    dishType: "food",
    cuisine: "North African",
    category: "Mains",
    dietTags: ["gluten-free", "dairy-free", "pescatarian"],
    moodTags: ["quick", "fresh", "post-gym"],
    difficulty: "easy",
    prepMinutes: 10,
    cookMinutes: 20,
    servings: 4,
    heroImage: "",
    heroAlt: "Salmon fillets glazed with harissa over chickpeas and cherry tomatoes",
    intro:
      "A sheet pan dinner with a glaze that caramelizes at the edges. Chickpeas and tomatoes roast underneath and soak up everything that drips down.",
    ingredients: [
      { quantity: 4, unit: null, item: "salmon fillets" },
      { quantity: 2, unit: "tbsp", item: "harissa paste" },
      { quantity: 1, unit: "tbsp", item: "honey", pantry: true },
      { quantity: 1, unit: "can", item: "chickpeas", note: "drained" },
      { quantity: 300, unit: "g", item: "cherry tomatoes" },
      { quantity: 2, unit: "tbsp", item: "olive oil", pantry: true },
      { quantity: 1, unit: null, item: "lemon", pantry: true },
      { quantity: null, unit: null, item: "parsley and yogurt", note: "to serve" },
    ],
    steps: [
      { instruction: "Heat the oven to 210C. Toss chickpeas and tomatoes with oil and salt on a tray and roast for ten minutes.", durationMinutes: 10 },
      { instruction: "Stir harissa with honey and a little oil. Coat the salmon fillets on all sides.", durationMinutes: 3 },
      { instruction: "Nestle the salmon into the tray and roast until it flakes but is still glossy in the middle.", durationMinutes: 10 },
      { instruction: "Finish with lemon, parsley, and a spoon of yogurt to cool the heat.", durationMinutes: 2 },
    ],
    equipment: ["Sheet pan"],
    tips: ["Firm white fish or thick tofu slabs take the same glaze and timing."],
    nutrition: { calories: 480, protein: 39, carbs: 22, fat: 27, sugar: 8, fiber: 6 },
    flavor: { sweet: 4, salty: 5, sour: 4, bitter: 1, umami: 6, fat: 6, spicy: 6 },
    author: "The Dish It Kitchen",
    featured: false,
    publishedAt: "2026-04-02",
  },
  {
    _id: "seed-dal-tadka",
    slug: "silky-dal-tadka",
    title: "Silky Dal Tadka",
    dishType: "food",
    cuisine: "Indian",
    category: "Mains",
    dietTags: ["vegan", "gluten-free", "dairy-free"],
    moodTags: ["cozy", "comfort", "post-gym"],
    difficulty: "easy",
    prepMinutes: 10,
    cookMinutes: 35,
    servings: 4,
    heroImage: "",
    heroAlt: "A pot of yellow dal with a bright tempering of spices poured over the top",
    intro:
      "Comfort in a bowl. The lentils cook down until creamy, then a sizzling tadka of cumin, garlic, and chili gets poured over just before serving.",
    ingredients: [
      { quantity: 1.5, unit: "cups", item: "red lentils", note: "rinsed" },
      { quantity: 1, unit: null, item: "tomato", note: "chopped", pantry: true },
      { quantity: 0.5, unit: "tsp", item: "turmeric", pantry: true },
      { quantity: 3, unit: "tbsp", item: "ghee or oil", group: "Tadka", pantry: true },
      { quantity: 1, unit: "tsp", item: "cumin seeds", group: "Tadka", pantry: true },
      { quantity: 4, unit: null, item: "garlic cloves", note: "sliced", group: "Tadka", pantry: true },
      { quantity: 1, unit: null, item: "dried red chili", group: "Tadka" },
      { quantity: 1, unit: "tsp", item: "kashmiri chili powder", group: "Tadka" },
    ],
    steps: [
      { instruction: "Simmer the lentils with tomato, turmeric, and plenty of water until they collapse into a loose puree.", durationMinutes: 25, technique: "reduce" },
      { instruction: "Whisk to smooth it out and season with salt. Loosen with hot water if it tightens up.", durationMinutes: 2 },
      { instruction: "In a small pan, heat the ghee and add cumin. When it sputters, add garlic and chili and fry until golden.", durationMinutes: 3, technique: "bloom-spices" },
      { instruction: "Take the tadka off the heat, stir in the chili powder, and pour the whole thing over the dal.", durationMinutes: 1 },
    ],
    equipment: ["Saucepan", "Small tempering pan"],
    tips: ["A squeeze of lemon and a handful of coriander at the table keeps every bowl fresh."],
    nutrition: { calories: 360, protein: 18, carbs: 44, fat: 13, sugar: 4, fiber: 11 },
    flavor: { sweet: 2, salty: 5, sour: 3, bitter: 2, umami: 6, fat: 5, spicy: 4 },
    author: "The Dish It Kitchen",
    featured: false,
    publishedAt: "2026-01-08",
  },
  {
    _id: "seed-olive-oil-cake",
    slug: "salted-honey-olive-oil-cake",
    title: "Salted Honey Olive Oil Cake",
    dishType: "dessert",
    cuisine: "Mediterranean",
    category: "Baking",
    dietTags: ["vegetarian"],
    moodTags: ["celebration", "cozy", "indulgent"],
    difficulty: "medium",
    prepMinutes: 20,
    cookMinutes: 45,
    servings: 10,
    heroImage: "",
    heroAlt: "A single layer olive oil cake with a honey glaze and flaky salt",
    intro:
      "Moist for days and barely sweet, this is the cake for people who say they do not like cake. A honey glaze soaks in while it is still warm.",
    ingredients: [
      { quantity: 1, unit: "cup", item: "extra virgin olive oil", pantry: true },
      { quantity: 1, unit: "cup", item: "sugar", pantry: true },
      { quantity: 3, unit: null, item: "eggs" },
      { quantity: 0.75, unit: "cup", item: "milk" },
      { quantity: 0.25, unit: "cup", item: "honey", pantry: true },
      { quantity: 1.75, unit: "cups", item: "flour", pantry: true },
      { quantity: 1.5, unit: "tsp", item: "baking powder", pantry: true },
      { quantity: 1, unit: null, item: "orange", note: "zest" },
      { quantity: null, unit: null, item: "flaky salt", note: "to finish", pantry: true },
    ],
    steps: [
      { instruction: "Heat the oven to 175C and line a round tin. Whisk oil, sugar, and eggs until pale and thick.", durationMinutes: 4 },
      { instruction: "Whisk in the milk and orange zest, then fold the flour and baking powder through in two additions.", durationMinutes: 3, technique: "fold" },
      { instruction: "Pour into the tin and bake until a skewer comes out with a few moist crumbs.", durationMinutes: 42 },
      { instruction: "Warm the honey with a splash of water and brush it over the hot cake. Finish with flaky salt once cooled.", durationMinutes: 5 },
    ],
    equipment: ["23cm round tin", "Whisk"],
    tips: ["Use an olive oil you would happily drizzle on bread. The flavor carries straight through."],
    nutrition: { calories: 390, protein: 5, carbs: 44, fat: 22, sugar: 27, fiber: 1 },
    flavor: { sweet: 7, salty: 3, sour: 2, bitter: 2, umami: 1, fat: 7, spicy: 0 },
    author: "The Dish It Kitchen",
    featured: true,
    publishedAt: "2026-02-14",
  },
  {
    _id: "seed-tahini-cookies",
    slug: "dark-chocolate-tahini-cookies",
    title: "Dark Chocolate Tahini Cookies",
    dishType: "dessert",
    cuisine: "Middle Eastern",
    category: "Baking",
    dietTags: ["vegetarian"],
    moodTags: ["quick", "indulgent", "comfort"],
    difficulty: "easy",
    prepMinutes: 15,
    cookMinutes: 12,
    servings: 18,
    heroImage: "",
    heroAlt: "Crackle topped chocolate cookies with a nutty tahini swirl",
    intro:
      "Fudgy in the center with a paper thin crackle on top. Tahini keeps them from being too rich and adds a savory hum you cannot quite place.",
    ingredients: [
      { quantity: 0.5, unit: "cup", item: "tahini", note: "well stirred" },
      { quantity: 0.5, unit: "cup", item: "butter", note: "softened", pantry: true },
      { quantity: 1, unit: "cup", item: "brown sugar", pantry: true },
      { quantity: 1, unit: null, item: "egg" },
      { quantity: 1.25, unit: "cups", item: "flour", pantry: true },
      { quantity: 0.5, unit: "cup", item: "cocoa powder", pantry: true },
      { quantity: 0.5, unit: "tsp", item: "baking soda", pantry: true },
      { quantity: 150, unit: "g", item: "dark chocolate", note: "chopped" },
      { quantity: null, unit: null, item: "sesame seeds", note: "for rolling" },
    ],
    steps: [
      { instruction: "Beat tahini, butter, and brown sugar until fluffy, then beat in the egg.", durationMinutes: 4 },
      { instruction: "Fold in the flour, cocoa, and baking soda, then the chopped chocolate. Chill the dough.", durationMinutes: 30, technique: "fold" },
      { instruction: "Roll walnut sized balls in sesame seeds and space them well on lined trays.", durationMinutes: 8 },
      { instruction: "Bake at 180C until the edges are set but the middles still look underdone. They firm as they cool.", durationMinutes: 11 },
    ],
    equipment: ["Hand mixer", "Baking trays"],
    tips: ["Underbaking by a minute is the difference between a good cookie and a great one."],
    nutrition: { calories: 180, protein: 3, carbs: 22, fat: 10, sugar: 14, fiber: 2 },
    flavor: { sweet: 6, salty: 3, sour: 1, bitter: 5, umami: 2, fat: 6, spicy: 0 },
    author: "The Dish It Kitchen",
    featured: false,
    publishedAt: "2026-03-08",
  },
  {
    _id: "seed-strawberry-ice-cream",
    slug: "no-churn-roasted-strawberry-ice-cream",
    title: "No Churn Roasted Strawberry Ice Cream",
    dishType: "dessert",
    cuisine: "American",
    category: "Frozen",
    dietTags: ["vegetarian", "gluten-free"],
    moodTags: ["celebration", "fresh", "indulgent"],
    difficulty: "easy",
    prepMinutes: 20,
    cookMinutes: 25,
    servings: 8,
    heroImage: "",
    heroAlt: "Scoops of pink strawberry ice cream with visible fruit ripples",
    intro:
      "Roasting the berries first drives off water and concentrates their flavor, so the finished scoop tastes like summer even in January. No machine required.",
    ingredients: [
      { quantity: 500, unit: "g", item: "strawberries", note: "hulled and halved" },
      { quantity: 0.25, unit: "cup", item: "sugar", pantry: true },
      { quantity: 1, unit: null, item: "lemon", note: "juice", pantry: true },
      { quantity: 2, unit: "cups", item: "heavy cream", note: "cold" },
      { quantity: 1, unit: "can", item: "sweetened condensed milk", note: "chilled" },
      { quantity: 1, unit: "pinch", item: "salt", pantry: true },
    ],
    steps: [
      { instruction: "Roast the strawberries with sugar at 200C until jammy and slightly caramelized, then cool and mash.", durationMinutes: 25 },
      { instruction: "Whip the cold cream to firm peaks. In another bowl stir the condensed milk with lemon and salt.", durationMinutes: 5 },
      { instruction: "Fold the cream into the condensed milk in three additions to keep it airy.", durationMinutes: 3, technique: "fold" },
      { instruction: "Ripple the strawberry through the base, freeze in a loaf tin, and cover the surface with parchment.", durationMinutes: 5 },
    ],
    equipment: ["Stand or hand mixer", "Loaf tin"],
    tips: ["Freeze at least six hours. Overnight is better and it scoops cleanly after five minutes on the counter."],
    nutrition: { calories: 340, protein: 5, carbs: 34, fat: 21, sugar: 32, fiber: 1 },
    flavor: { sweet: 8, salty: 2, sour: 4, bitter: 0, umami: 1, fat: 7, spicy: 0 },
    author: "The Dish It Kitchen",
    featured: false,
    publishedAt: "2026-04-10",
  },
  {
    _id: "seed-pb-banana-shake",
    slug: "peanut-butter-banana-recovery-shake",
    title: "Peanut Butter Banana Recovery Shake",
    dishType: "shake",
    cuisine: "American",
    category: "Shakes",
    dietTags: ["vegetarian", "gluten-free"],
    moodTags: ["post-gym", "quick", "comfort"],
    difficulty: "easy",
    prepMinutes: 5,
    cookMinutes: 0,
    servings: 1,
    heroImage: "",
    heroAlt: "A thick tan milkshake with a peanut butter drizzle down the glass",
    intro:
      "The one to blend after a hard session. Real numbers on the protein, enough carbs to actually refuel, and it tastes like a milkshake you would order on purpose.",
    ingredients: [
      { quantity: 1, unit: null, item: "frozen banana" },
      { quantity: 1, unit: "scoop", item: "vanilla whey" },
      { quantity: 1, unit: "tbsp", item: "natural peanut butter" },
      { quantity: 1, unit: "cup", item: "oat milk" },
      { quantity: 1, unit: "tsp", item: "cocoa powder", note: "optional", pantry: true },
      { quantity: 4, unit: null, item: "ice cubes" },
    ],
    steps: [
      { instruction: "Add the oat milk first so the blades catch, then everything else on top.", durationMinutes: 1 },
      { instruction: "Blend on high until completely smooth and the ice is gone, about forty seconds.", durationMinutes: 1 },
      { instruction: "Pour into a cold glass. Streak the inside with extra peanut butter first if you want the diner look.", durationMinutes: 1 },
    ],
    equipment: ["Blender"],
    tips: ["Swap whey for a scoop of silken tofu and a date to keep it fully plant based."],
    nutrition: { calories: 420, protein: 32, carbs: 44, fat: 14, sugar: 22, fiber: 6 },
    flavor: { sweet: 7, salty: 3, sour: 1, bitter: 2, umami: 2, fat: 6, spicy: 0 },
    author: "The Dish It Kitchen",
    featured: true,
    publishedAt: "2026-02-01",
  },
  {
    _id: "seed-green-glow-shake",
    slug: "green-glow-pineapple-shake",
    title: "Green Glow Pineapple Shake",
    dishType: "shake",
    cuisine: "Tropical",
    category: "Shakes",
    dietTags: ["vegan", "gluten-free", "dairy-free"],
    moodTags: ["fresh", "quick", "post-gym"],
    difficulty: "easy",
    prepMinutes: 5,
    cookMinutes: 0,
    servings: 1,
    heroImage: "",
    heroAlt: "A vivid green shake with a pineapple wedge on the rim",
    intro:
      "Bright, not grassy. Pineapple and lime do the heavy lifting so the spinach just rides along for the color and the iron.",
    ingredients: [
      { quantity: 1, unit: "cup", item: "frozen pineapple" },
      { quantity: 2, unit: "cups", item: "baby spinach", note: "packed" },
      { quantity: 0.5, unit: null, item: "frozen banana" },
      { quantity: 1, unit: "cup", item: "coconut water" },
      { quantity: 1, unit: null, item: "lime", note: "juice", pantry: true },
      { quantity: 1, unit: "tsp", item: "grated ginger", pantry: true },
    ],
    steps: [
      { instruction: "Blend the spinach with the coconut water first until no flecks remain.", durationMinutes: 1 },
      { instruction: "Add the frozen fruit, lime, and ginger and blend again until thick and pourable.", durationMinutes: 1 },
      { instruction: "Taste and adjust with more lime for zip or banana for body.", durationMinutes: 1 },
    ],
    equipment: ["Blender"],
    tips: ["Freeze leftover shake in a lolly mould for a two ingredient feeling dessert."],
    nutrition: { calories: 230, protein: 5, carbs: 48, fat: 2, sugar: 30, fiber: 8 },
    flavor: { sweet: 6, salty: 1, sour: 6, bitter: 2, umami: 1, fat: 1, spicy: 2 },
    author: "The Dish It Kitchen",
    featured: false,
    publishedAt: "2026-03-25",
  },
  {
    _id: "seed-coffee-malt",
    slug: "cold-brew-coffee-malt",
    title: "Cold Brew Coffee Malt",
    dishType: "shake",
    cuisine: "American",
    category: "Shakes",
    dietTags: ["vegetarian"],
    moodTags: ["indulgent", "cozy", "quick"],
    difficulty: "easy",
    prepMinutes: 5,
    cookMinutes: 0,
    servings: 2,
    heroImage: "",
    heroAlt: "A retro coffee malt shake with whipped cream and a straw",
    intro:
      "A grown up malted shake. Cold brew keeps it from being cloying and the malt powder gives that old soda fountain roundness.",
    ingredients: [
      { quantity: 3, unit: "scoops", item: "vanilla ice cream" },
      { quantity: 0.5, unit: "cup", item: "cold brew concentrate" },
      { quantity: 0.25, unit: "cup", item: "milk" },
      { quantity: 2, unit: "tbsp", item: "malted milk powder" },
      { quantity: 1, unit: "pinch", item: "salt", pantry: true },
      { quantity: null, unit: null, item: "whipped cream", note: "to serve" },
    ],
    steps: [
      { instruction: "Blend everything except the whipped cream in short pulses so it stays thick.", durationMinutes: 1 },
      { instruction: "Check the texture. It should be spoonable at first and drinkable after a minute.", durationMinutes: 1 },
      { instruction: "Pour into chilled glasses and top with whipped cream and a dusting of extra malt.", durationMinutes: 1 },
    ],
    equipment: ["Blender"],
    tips: ["No malt powder means a fine classic coffee shake. It is not the same, but nobody complains."],
    nutrition: { calories: 330, protein: 8, carbs: 38, fat: 16, sugar: 32, fiber: 1 },
    flavor: { sweet: 7, salty: 3, sour: 1, bitter: 5, umami: 2, fat: 6, spicy: 0 },
    author: "The Dish It Kitchen",
    featured: false,
    publishedAt: "2026-04-05",
  },
  {
    _id: "seed-hibiscus-cooler",
    slug: "hibiscus-ginger-cooler",
    title: "Hibiscus Ginger Cooler",
    dishType: "drink",
    cuisine: "Global",
    category: "Coolers",
    dietTags: ["vegan", "gluten-free", "dairy-free"],
    moodTags: ["fresh", "celebration", "quick"],
    difficulty: "easy",
    prepMinutes: 10,
    cookMinutes: 10,
    servings: 6,
    heroImage: "",
    heroAlt: "A jug of deep magenta hibiscus cooler over ice with lime",
    intro:
      "Tart, floral, and the most striking color in the fridge. Brew it strong, sweeten lightly, and let everyone cut it with soda to taste.",
    ingredients: [
      { quantity: 0.5, unit: "cup", item: "dried hibiscus flowers" },
      { quantity: 1, unit: "l", item: "water" },
      { quantity: 1, unit: "thumb", item: "ginger", note: "sliced", pantry: true },
      { quantity: 0.3, unit: "cup", item: "honey or sugar", pantry: true },
      { quantity: 2, unit: null, item: "limes", pantry: true },
      { quantity: null, unit: null, item: "soda water and mint", note: "to serve" },
    ],
    steps: [
      { instruction: "Simmer the hibiscus and ginger in the water for ten minutes, then take it off the heat.", durationMinutes: 10 },
      { instruction: "Stir in the sweetener while warm so it dissolves, then steep another ten minutes.", durationMinutes: 10 },
      { instruction: "Strain and chill. Add lime juice once cold so it stays bright.", durationMinutes: 2 },
      { instruction: "Serve over ice, half concentrate and half soda, with a slap of mint.", durationMinutes: 2 },
    ],
    equipment: ["Saucepan", "Fine sieve"],
    tips: ["The spent flowers are not trash. Chop and simmer with sugar for a quick jammy topping."],
    nutrition: { calories: 60, protein: 0, carbs: 16, fat: 0, sugar: 14, fiber: 0 },
    flavor: { sweet: 5, salty: 0, sour: 8, bitter: 3, umami: 0, fat: 0, spicy: 2 },
    author: "The Dish It Kitchen",
    featured: true,
    publishedAt: "2026-01-30",
  },
  {
    _id: "seed-agua-fresca",
    slug: "cucumber-mint-agua-fresca",
    title: "Cucumber Mint Agua Fresca",
    dishType: "drink",
    cuisine: "Mexican",
    category: "Coolers",
    dietTags: ["vegan", "gluten-free", "dairy-free"],
    moodTags: ["fresh", "quick", "post-gym"],
    difficulty: "easy",
    prepMinutes: 10,
    cookMinutes: 0,
    servings: 4,
    heroImage: "",
    heroAlt: "A pale green cucumber agua fresca with mint and lime wheels",
    intro:
      "The most refreshing thing you can make in five minutes. Blend, strain, chill. It tastes like the inside of a cucumber, in the best way.",
    ingredients: [
      { quantity: 2, unit: null, item: "large cucumbers", note: "chopped" },
      { quantity: 3, unit: "cups", item: "cold water" },
      { quantity: 1, unit: "small handful", item: "mint leaves" },
      { quantity: 2, unit: null, item: "limes", note: "juice", pantry: true },
      { quantity: 2, unit: "tbsp", item: "agave or sugar", pantry: true },
      { quantity: 1, unit: "pinch", item: "salt", pantry: true },
    ],
    steps: [
      { instruction: "Blend the cucumber with the water and mint until completely liquid.", durationMinutes: 1 },
      { instruction: "Strain through a sieve, pressing the solids to get every drop.", durationMinutes: 2 },
      { instruction: "Stir in lime, sweetener, and a tiny pinch of salt to make the flavor pop. Chill well.", durationMinutes: 2 },
    ],
    equipment: ["Blender", "Sieve"],
    tips: ["Leave the skin on one cucumber for a greener color and a little more structure."],
    nutrition: { calories: 40, protein: 1, carbs: 10, fat: 0, sugar: 7, fiber: 1 },
    flavor: { sweet: 4, salty: 1, sour: 6, bitter: 1, umami: 0, fat: 0, spicy: 0 },
    author: "The Dish It Kitchen",
    featured: false,
    publishedAt: "2026-04-12",
  },
  {
    _id: "seed-golden-milk",
    slug: "spiced-golden-milk",
    title: "Spiced Golden Milk",
    dishType: "drink",
    cuisine: "Indian",
    category: "Warm drinks",
    dietTags: ["vegan-option", "gluten-free"],
    moodTags: ["cozy", "comfort", "celebration"],
    difficulty: "easy",
    prepMinutes: 5,
    cookMinutes: 10,
    servings: 2,
    heroImage: "",
    heroAlt: "Two mugs of golden turmeric milk with a cinnamon stick",
    intro:
      "A bedtime mug that actually earns its place. Simmering the spices in fat, then whisking hard, is what turns this from dusty to silky.",
    ingredients: [
      { quantity: 2, unit: "cups", item: "milk of choice" },
      { quantity: 1, unit: "tsp", item: "turmeric", pantry: true },
      { quantity: 0.5, unit: "tsp", item: "cinnamon", pantry: true },
      { quantity: 1, unit: "pinch", item: "black pepper", pantry: true },
      { quantity: 1, unit: "thumb", item: "ginger", note: "grated", pantry: true },
      { quantity: 1, unit: "tsp", item: "coconut oil or ghee", pantry: true },
      { quantity: 2, unit: "tsp", item: "honey or maple", pantry: true },
    ],
    steps: [
      { instruction: "Warm the fat in a small pot and add the turmeric, cinnamon, pepper, and ginger. Stir for thirty seconds.", durationMinutes: 1, technique: "bloom-spices" },
      { instruction: "Pour in the milk and bring to a bare simmer, whisking so nothing catches.", durationMinutes: 6 },
      { instruction: "Whisk hard for a full minute to froth it, then sweeten off the heat and strain into mugs.", durationMinutes: 2 },
    ],
    equipment: ["Small saucepan", "Whisk"],
    tips: ["The pinch of pepper is not optional. It is what makes the turmeric actually do something."],
    nutrition: { calories: 150, protein: 6, carbs: 18, fat: 6, sugar: 16, fiber: 1 },
    flavor: { sweet: 6, salty: 1, sour: 0, bitter: 3, umami: 1, fat: 4, spicy: 3 },
    author: "The Dish It Kitchen",
    featured: false,
    publishedAt: "2026-01-15",
  },
];
